# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4  # Use the ruff version you have installed
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        exclude: ^src/auto_generated/
      # Run the formatter
      - id: ruff-format
        exclude: ^src/auto_generated/

  # Check for common issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: mixed-line-ending

  # Build check
  - repo: local
    hooks:
      - id: uv-build
        name: Build package check
        entry: uv build
        language: system
        pass_filenames: false
        always_run: true
